// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(LoterieDbContext))]
    partial class LoterieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Models.Game", b =>
                {
                    b.Property<int>("game_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("game_id"));

                    b.Property<DateTime>("GetCurrentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("choux")
                        .HasColumnType("int");

                    b.Property<string>("num_draw")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("game_id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DataLayer.Models.Player", b =>
                {
                    b.Property<int>("player_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("player_id"));

                    b.Property<int>("game_id")
                        .HasColumnType("int");

                    b.Property<string>("guid_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("num_draw_player")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("player_id");

                    b.HasIndex("game_id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DataLayer.Models.Player", b =>
                {
                    b.HasOne("DataLayer.Models.Game", "game")
                        .WithMany("players")
                        .HasForeignKey("game_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("game");
                });

            modelBuilder.Entity("DataLayer.Models.Game", b =>
                {
                    b.Navigation("players");
                });
#pragma warning restore 612, 618
        }
    }
}
